### ISSUE TITLE
Error	CA1816	Change ResizeObserverService.DisposeAsync() to call GC.SuppressFinalize(object).

### ISSUE THREAD

**Issue by MilesGibson** [xaviersolau/BlazorLayout#11]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CA1816	Change ResizeObserverService.DisposeAsync() to call GC.SuppressFinalize(object). This will prevent derived types that introduce a finalizer from needing to re-implement 'IDisposable' to call it.	SoloX.BlazorLayout	C:\Users\super\Downloads\BlazorLayout-main\BlazorLayout-main\src\libs\SoloX.BlazorLayout\Services\Impl\ResizeObserverService.cs	133	Active

**Comment by xaviersolau** [comment]
Hi, thanks for your feedback!
I will fix it but could you tell me how you got this error exactly?

**Comment by xaviersolau** [comment]
ok I will install SDK Net 6.0 rc2 and I will see if I can reproduce....

**Comment by MilesGibson** [comment]
Here is an idea for you:

 

Create VS Project Templates for users.  So then I am starting with a blank solution that is already Responsive ready.  You could even charge for this I think.

 

Thoughts?

 

Miles

**Comment by xaviersolau** [comment]
Well, yes... this could be a good idea... I will consider this!
Thanks for your feedback and don't hesitate if you have any issue.
