### ISSUE TITLE
Setup error?

### ISSUE THREAD

**Issue by nicvdb** [xaviersolau/BlazorLayout#13]
Hi, 
wanted to use BlazorLayout.
Followed the instructions, installed the package reference, added the directives , but I get the following error:

> Found markup element with unexpected name 'ResponsiveLayout'. If this is intended to be a component, add a @using directive for its namespace.(RZ10012)

What did I miss?

Thx, Nic

**Comment by xaviersolau** [comment]
well it looks like the compiler can't resolve the ResponsiveLayout namespace.
did you add the using directive in your _Imports.razor? (@using SoloX.BlazorLayout.Layouts)

you also can try to add the directive directly in the razor file using the ResponsiveLayout...

Hope this help....

**Comment by nicvdb** [comment]
Thx, that did the job.

**Comment by nicvdb** [comment]
Hi Xavier,

Just 2 question:

  *   How do I specify the height (or other properties) of eg the Header or Footer in CSS?
  *   I've a component with a row with buttons (dynamically generated, so might end up in 2 rows) I want to place vertically centered in the ChildContent. How do I make sure it's centered, whatever the number of rows is?

Thx for helping a newbie.

Nic

**Comment by xaviersolau** [comment]
Well, in order to specify the height of your Header/Footer you can directly use the Style property:
```razor
    <Header>
        <BoxContainer Fill="Fill.Full" Style="height:500px;">
            @* Your header.... *@
        </BoxContainer>
    </Header>

```

**Comment by xaviersolau** [comment]
and in order to center vertically you can try this option:

```razor
<BoxContainer Fill="Fill.Full" Style="display: grid; align-items: center;">
     @* the content to center vertically *@
 </BoxContainer>
```

Hope it helps...
