### ISSUE TITLE
Vertical Scroll Bars

### ISSUE THREAD

**Issue by nicvdb** [xaviersolau/BlazorLayout#14]
I have large component with a header and several rows (number of rows are dynamic).
I want to put this in the ChildContent of the MainLayout. 
The header should be fixed in the ChildContent and I want to see a vertical scroll bar on the part that shows the rows (and only on that part, not on the full page.

Can this be done using DockContainer or BoxContainer? Tried both of them, but I always get a scroll bar for the full ChildContent. So the header within the ChildContent (or the DockPanel when using DockContainer) scrolls too.

This is how it should look.

Thx for the help.
![image](https://user-images.githubusercontent.com/78236804/148841780-7275a1ff-cbab-46a9-881e-97855c55db43.png)

**Comment by xaviersolau** [comment]
Did you try the EnableContentScroll property on the ResponsiveLayout component?

You can see it in action:
when it's false:
![image](https://user-images.githubusercontent.com/15972064/148853255-ff64da40-a000-4cd1-b31a-594c9276a9f8.png)

and when it's true:

![image](https://user-images.githubusercontent.com/15972064/148853330-d976d792-4f46-47a6-ae68-9ccc2380c702.png)

Then in the ChildContent you can use a DockContainer, I think it should work.

Hope this help.
